import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.guest}>
        <Navbar/>
        <HomeHeader/>
      </main>
    </>
  )
}

const HomeHeader = () => {
  return (
    <div className={styles.header}>
      <h1>Company Name Here</h1>
      <p>Everything you need to run your college organization</p>
    </div>
  )
}
