import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();
  const router = useRouter();
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    if (session) {
      router.push('/dashboard');
    } else {
      setLoading(false);
    }
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <div>
        </div>
      ) : (
        <main className={styles.guest}>
          <Navbar/>
          <HomeHeader/>
        </main>
      )}
    </div>
  )
}

const HomeHeader = () => {
  return (
    <div className={styles.header}>
      <h1>Company Name Here</h1>
      <p>Everything you need to run your college organization</p>
    </div>
  )
}
